action_id: trunk-share-with-everyone
date: 2025-10-09 04:16:05
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-share-with-everyone'. See .trunk\out\OnilM.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\OnilM.yaml
timestamp: 1759983365
full_timestamp:
  nanos: 181588000
  seconds: 1759983365
trunk_version: 1.25.0
