action_id: trunk-cache-prune
date: 2025-10-09 04:16:05
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-cache-prune'. See .trunk\out\NhXxK.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\NhXxK.yaml
timestamp: 1759983365
full_timestamp:
  nanos: 181447000
  seconds: 1759983365
trunk_version: 1.25.0
