action_id: trunk-cache-prune
date: 2025-10-09 23:18:22
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-cache-prune'. See .trunk\out\jwciP.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\jwciP.yaml
timestamp: 1760051902
full_timestamp:
  nanos: 374909000
  seconds: 1760051902
trunk_version: 1.25.0
