action_id: trunk-upgrade-available
date: 2025-10-08 11:07:21
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\GxvYv.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\GxvYv.yaml
timestamp: 1759921641
full_timestamp:
  nanos: 717474000
  seconds: 1759921641
trunk_version: 1.25.0
