action_id: trunk-upgrade-available
date: 2025-10-08 18:24:03
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\NPrxR.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\NPrxR.yaml
timestamp: 1759947843
full_timestamp:
  nanos: 646273000
  seconds: 1759947843
trunk_version: 1.25.0
