action_id: trunk-upgrade-available
date: 2025-10-08 10:07:21
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\FTw2d.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\FTw2d.yaml
timestamp: 1759918041
full_timestamp:
  nanos: 707576000
  seconds: 1759918041
trunk_version: 1.25.0
