action_id: trunk-upgrade-available
date: 2025-10-12 04:16:08
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\SX3H6.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\SX3H6.yaml
timestamp: 1760242568
full_timestamp:
  nanos: 496713000
  seconds: 1760242568
trunk_version: 1.25.0
