action_id: trunk-upgrade-available
date: 2025-10-10 17:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\UvI7U.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\UvI7U.yaml
timestamp: 1760116565
full_timestamp:
  nanos: 189529000
  seconds: 1760116565
trunk_version: 1.25.0
