action_id: trunk-upgrade-available
date: 2025-10-12 10:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\DTIYe.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\DTIYe.yaml
timestamp: 1760264165
full_timestamp:
  nanos: 185913000
  seconds: 1760264165
trunk_version: 1.25.0
