action_id: trunk-upgrade-available
date: 2025-10-09 06:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\3WGOx.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\3WGOx.yaml
timestamp: 1759990565
full_timestamp:
  nanos: 203085000
  seconds: 1759990565
trunk_version: 1.25.0
