action_id: trunk-upgrade-available
date: 2025-10-09 16:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\QKcTe.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\QKcTe.yaml
timestamp: 1760026565
full_timestamp:
  nanos: 231149000
  seconds: 1760026565
trunk_version: 1.25.0
