action_id: trunk-upgrade-available
date: 2025-10-08 13:07:21
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\6qu6o.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\6qu6o.yaml
timestamp: 1759928841
full_timestamp:
  nanos: 754684000
  seconds: 1759928841
trunk_version: 1.25.0
