action_id: trunk-upgrade-available
date: 2025-10-11 04:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\c06Zg.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\c06Zg.yaml
timestamp: 1760156165
full_timestamp:
  nanos: 145820000
  seconds: 1760156165
trunk_version: 1.25.0
