action_id: trunk-upgrade-available
date: 2025-10-11 13:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\9xsNj.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\9xsNj.yaml
timestamp: 1760188565
full_timestamp:
  nanos: 143084000
  seconds: 1760188565
trunk_version: 1.25.0
