action_id: trunk-upgrade-available
date: 2025-10-11 03:16:09
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\hEgX5.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\hEgX5.yaml
timestamp: 1760152569
full_timestamp:
  nanos: 787249000
  seconds: 1760152569
trunk_version: 1.25.0
