action_id: trunk-upgrade-available
date: 2025-10-08 15:07:21
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\TY38v.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\TY38v.yaml
timestamp: 1759936041
full_timestamp:
  nanos: 758879000
  seconds: 1759936041
trunk_version: 1.25.0
