action_id: trunk-upgrade-available
date: 2025-10-10 13:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\I2MG2.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\I2MG2.yaml
timestamp: 1760102165
full_timestamp:
  nanos: 166639000
  seconds: 1760102165
trunk_version: 1.25.0
