action_id: trunk-upgrade-available
date: 2025-10-09 17:16:09
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\OH2Rn.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\OH2Rn.yaml
timestamp: 1760030169
full_timestamp:
  nanos: 404427000
  seconds: 1760030169
trunk_version: 1.25.0
