action_id: trunk-upgrade-available
date: 2025-10-09 23:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\f2TIW.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\f2TIW.yaml
timestamp: 1760051765
full_timestamp:
  nanos: 146768000
  seconds: 1760051765
trunk_version: 1.25.0
