action_id: trunk-upgrade-available
date: 2025-10-10 03:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\NVcc8.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\NVcc8.yaml
timestamp: 1760066165
full_timestamp:
  nanos: 155803000
  seconds: 1760066165
trunk_version: 1.25.0
