action_id: trunk-upgrade-available
date: 2025-10-11 11:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\7filS.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\7filS.yaml
timestamp: 1760181365
full_timestamp:
  nanos: 166102000
  seconds: 1760181365
trunk_version: 1.25.0
