action_id: trunk-upgrade-available
date: 2025-10-09 15:30:31
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\Xvdx3.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\Xvdx3.yaml
timestamp: 1760023831
full_timestamp:
  nanos: 672421000
  seconds: 1760023831
trunk_version: 1.25.0
