action_id: trunk-upgrade-available
date: 2025-10-11 10:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\g7efM.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\g7efM.yaml
timestamp: 1760177765
full_timestamp:
  nanos: 154788000
  seconds: 1760177765
trunk_version: 1.25.0
