action_id: trunk-upgrade-available
date: 2025-10-09 22:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\oMLzq.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\oMLzq.yaml
timestamp: 1760048165
full_timestamp:
  nanos: 142115000
  seconds: 1760048165
trunk_version: 1.25.0
