action_id: trunk-upgrade-available
date: 2025-10-09 21:30:55
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\MRUgL.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\MRUgL.yaml
timestamp: 1760045455
full_timestamp:
  nanos: 990594000
  seconds: 1760045455
trunk_version: 1.25.0
