action_id: trunk-upgrade-available
date: 2025-10-08 09:07:21
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\WEV74.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\WEV74.yaml
timestamp: 1759914441
full_timestamp:
  nanos: 723682000
  seconds: 1759914441
trunk_version: 1.25.0
