action_id: trunk-upgrade-available
date: 2025-10-11 18:16:31
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\IsLKg.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\IsLKg.yaml
timestamp: 1760206591
full_timestamp:
  nanos: 782171000
  seconds: 1760206591
trunk_version: 1.25.0
