action_id: trunk-upgrade-available
date: 2025-10-08 17:10:38
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\Plg4W.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\Plg4W.yaml
timestamp: 1759943438
full_timestamp:
  nanos: 834624000
  seconds: 1759943438
trunk_version: 1.25.0
