action_id: trunk-upgrade-available
date: 2025-10-11 02:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\eC6KA.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\eC6KA.yaml
timestamp: 1760148965
full_timestamp:
  nanos: 162360000
  seconds: 1760148965
trunk_version: 1.25.0
