action_id: trunk-upgrade-available
date: 2025-10-09 07:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\HlReU.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\HlReU.yaml
timestamp: 1759994165
full_timestamp:
  nanos: 164281000
  seconds: 1759994165
trunk_version: 1.25.0
