action_id: trunk-upgrade-available
date: 2025-10-12 14:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\HEUD6.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\HEUD6.yaml
timestamp: 1760278565
full_timestamp:
  nanos: 205840000
  seconds: 1760278565
trunk_version: 1.25.0
