action_id: trunk-upgrade-available
date: 2025-10-09 05:16:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\D1PtG.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\D1PtG.yaml
timestamp: 1759986965
full_timestamp:
  nanos: 196634000
  seconds: 1759986965
trunk_version: 1.25.0
