action_id: trunk-single-player-auto-on-upgrade
date: 2025-10-11 23:23:22
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-single-player-auto-on-upgrade'. See .trunk\out\YfNR7.yaml for details.
  error_path: C:\Projects\phts\graft-loss-parallel-processing\.trunk\out\YfNR7.yaml
timestamp: 1760225002
full_timestamp:
  nanos: 382553000
  seconds: 1760225002
trunk_version: 1.25.0
